name: Build Docker Images

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Login to GitHub Packages Docker Registry
              uses: docker/login-action@v1
              with:
                  registry: docker.pkg.github.com
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build API Docker Image
              uses: docker/build-push-action@v2.3.0
              with:
                  push: true
                  tags: |
                      docker.pkg.github.com/hadermite/apollo-11-discord-bot/app:latest
